/**
 * Reads `.env` (falling back to `.env.example` if `.env` doesn't exist yet,
 * so a fresh checkout still builds) and writes
 * src/environments/environment.ts and environment.prod.ts as plain TS
 * objects. Run automatically before `start`/`build` via npm pre-hooks, or
 * manually via `npm run generate-env`.
 */
const fs = require('fs');
const path = require('path');

const envPath = fs.existsSync(path.join(__dirname, '..', '.env'))
  ? path.join(__dirname, '..', '.env')
  : path.join(__dirname, '..', '.env.example');

require('dotenv').config({ path: envPath });

const toBool = (v, fallback) => (v === undefined ? fallback : v === 'true');
const toNum = (v, fallback) => (v === undefined ? fallback : parseInt(v, 10));

function buildEnvObject(production) {
  return {
    production,
    apiBaseUrl: process.env.API_BASE_URL ?? 'http://localhost:3000/api/v1',
    loggingEnabled: toBool(process.env.LOGGING_ENABLED, true),
    paginationDefaultLimit: toNum(process.env.PAGINATION_DEFAULT_LIMIT, 10),
    authTokenStorageKey: process.env.AUTH_TOKEN_STORAGE_KEY ?? 'emp_mgmt_access_token',
    authRefreshStorageKey: process.env.AUTH_REFRESH_STORAGE_KEY ?? 'emp_mgmt_refresh_token',
    authBypass: toBool(process.env.AUTH_BYPASS, false),
    searchDebounceMs: toNum(process.env.SEARCH_DEBOUNCE_MS, 400),
  };
}

function writeEnvFile(filename, obj) {
  const contents = `// AUTO-GENERATED by scripts/generate-env.js from .env — do not edit directly.
export const environment = ${JSON.stringify(obj, null, 2)};
`;
  fs.writeFileSync(path.join(__dirname, '..', 'src', 'environments', filename), contents);
  console.log(`Wrote src/environments/${filename}`);
}

const devEnv = buildEnvObject(toBool(process.env.PRODUCTION, false));
const prodEnv = buildEnvObject(true);

// Production build never allows AUTH_BYPASS, mirroring the backend's
// hard block on JWT_BYPASS when NODE_ENV=production.
if (prodEnv.authBypass) {
  console.warn('AUTH_BYPASS=true is ignored in the production environment file.');
  prodEnv.authBypass = false;
}

writeEnvFile('environment.ts', devEnv);
writeEnvFile('environment.prod.ts', prodEnv);
